config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #root "customers#index"
  root "categories#index"
  #root "products#index"

  #resources :customers

  resources :categories do
    resources :products do 
      resources :orders
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, presence: true #uniqueness: true, length: { maximum: 30 }
  validates :description, presence: true, length: { maximum: 150 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  #before_save :valid_quantity

  #validates :quantity, presence: true

  # def valid_quantity

  #   if quantity > product.quantity
  #     errors.add(:quantity, "can't be greater the product quantity")
  #   end
  # end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  belongs_to :category


  validates :name, presence: true, uniqueness: true, length: { maximum: 30 }
  validates :description, length: { maximum: 150 }
  validates :rating, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  validates :quantity, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :print_display_message

  after_action :after_display_message



    private
    def print_display_message
      puts "I am before action."
    end
    def after_display_message
      puts "I am after action."
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # layout 'admin'
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = Category.all
    # render json: @categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_param)
    if @category.save
      # CategoryMailer.with(category: @category).new_category.deliver_later
      CategoryMailer.new_category(@category).deliver_now
      redirect_to @category
    else
      render new
    end
  end

  def show
    @category = Category.includes(:products).find(params[:id])
  end

  def edit 
  end

  def update
    if @category.update(category_param)
      redirect_to @category
    else
      render edit
    end
  end
 
  def destroy
    @category.destroy
    redirect_to root_path
  end

  def search
    if params[:search].blank?
      redirect_to categories_path
    else
      @input = params[:search].downcase
      @results = Category.where("name LIKE ?", "%#{@input}%")
    end
  end

  private

  def category_param
    params.require(:category).permit(:name, :description)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[show edit update destroy]
  before_action :authenticate_customer!
  def index 
    @customers = Customer.all
    #render json: @customers
  end

  def new 
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      render json: @customer
    else 
      render json: { message: @customer.errors.messages}
    end
  end

  def show 
  end

  def edit
  end

  def update 
    if @customer.update(customer_params)
      render json: @customer
    else 
      render json: { message: @customer.errors.messages }
    end
  end
  
  def destroy
    if @customer.destroy
      render json: { message: "Customer data deleated" }
    else
      render json: { message: "Customer data not deleated" }
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :contact_number)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def create
    @category = Category.find(params[:category_id])
    @product = Product.find(params[:product_id])
    @order = @product.orders.create(order_params)
    redirect_to category_products_path(@product)
  end

  private
  def order_params
    params.require(:order).permit(:customer_id, :product_id, :quantity, :total_amount)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 

  def index
    @products = Product.all
    #render json: @products
  end 

  # def new 
  #   @product = Product.new
  # end

  def create
    @category = Category.find(params[:category_id])
    @product = @category.products.create(product_params)
    redirect_to category_path(@category)
  end

  # def show
  # end

  # def edit
  # end

  def update
    @category = Category.find(params[:category_id])
    @product = @category.product.find(params[:id])
    @product.update
    redirect_to category_path(@category)

  end

  private
  def product_params
    params.require(:product).permit(:name, :description,
                                    :price, :quantity, :in_stock, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>

  <div class="form-group mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control from-control-lg" %>
    <% category.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control from-control-lg" %>
    <% category.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="form-group mt-3">
    <%= form.submit class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class= "col-lg-8 mx-auto">
  <div class="card shadow">
    <div class= "card-header">
      <h1 class="card-title">Edit Category</h1>
    </div>
    <div class="card-body">
       <%= render "form", category: @category %>
    </div>
  </div>  
</div>

app/views/categories/index.csv.erb
<%= fields = [:name, :description].join(";")%>

<%= @categories.each do |category|%>
  
  <% name = category.name %>
  <% description = category.description %>
  <%= [name, description].join(";") %>
<% end %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table class="table table-success table-striped-columns ml-4" style="max-width: 90rem;" >

  <thead  class="table table-dark">
	<tr>
  <th>ID</th>
  <th>Category Name</th>
  <th>Description</th>
  <th>Products</th>
  <th>Update</th>
  <th>Delete</th>
  </tr>
  </thead>

	<tbody>
  <% @categories.each do |category| %>
  <tr>
    <td><%= category.id %></td>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td><%= link_to "Products", category_products_path(category.id), class: "btn btn-info" %></td>
    <td><%= link_to "Update", edit_category_path(category.id), class: "btn btn-info" %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger ml-3" %></td>
  </tr>
  <% end %>
	</tbody>

</table>

<%= link_to "New Category", new_category_path, class: "btn btn-primary btn-lg mb-3" %>
<br>
<%= link_to "Download as CSV", categories_path(format: :csv), download: ["Categories", Date.today].join(""), class: "btn btn-info btn-lg" %>

app/views/categories/new.html.erb
<div class= "col-lg-8 mx-auto">
  <div class="card shadow">
    <div class= "card-header">
      <h1 class="card-title">New Category</h1>
    </div>
    <div class="card-body">
       <%= render "form", category: @category %>
    </div>
  </div>  
</div>

app/views/categories/search.html.erb
<h3>Category Search</h3>

<table class="table table-success table-striped-columns ml-4" style="max-width: 90rem;" >
  <thead  class="table table-dark">
	<tr>
  <th>ID</th>
  <th>Category Name</th>
  <th>Description</th>
  </tr>
  </thead>

	<tbody>
  <% @results.each do |result| %>
  <tr>
    <td><%= result.id %></td>
    <td><%= result.name %></td>
    <td><%= result.description %></td>
  </tr>
  <% end %>
	</tbody>

</table>

app/views/categories/show.html.erb
<div class="col-lg-8 mt-3">
  <div class="card shadow">
    <div class= "card-header">
      <p><%= @category.name %></p>

      <p><%= @category.description %></p>
    </div>
  </div>
  <div class="mt-2">
    <%= link_to "Destroy", category_path(@category), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, class: "btn btn-danger" %>
  </div>
</div>



app/views/customers/index.html.erb
<% if customer_signed_in? %> 
 <div> Welcome <%= current_customer.email %> </div> 
  <%= button_to "Sign out", destroy_customer_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_customer_session_path %> 
<% end %>

<h1> Custormers List </h1>

<ul>
  <% @customers.each do |customer| %>
    <li>
      <%= customer.name %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InventoryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

  <body>
  <%= render "shared/header"%>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  <%= render "shared/footer"%>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Order</h1>
<table class="table table-sm table-striped ml-4" style="max-width: 90rem;" >

  <thead  class="thead-dark">
	<tr>
    <th>Product ID</th>
    <th>Product Name</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>
  </thead>

	<tbody>
  <% @orders.each do |order| %>
  <tr>
    <td><%= product.id %></td>
    <td><%= product.name %></td>
    <td><%= order.quantity %></td>
    <td><%= product.price %></td>
  </tr>
  <% end %>
	</tbody>

</table>

app/views/products/index.html.erb
<h1>Products</h1>
<table class="table table-success table-striped" style="max-width: 90rem;" >

  <thead  class="table table-dark">
	<tr>
    <th>Select</th>
    <th>ID</th>
    <th>Product Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Rating</th>
    <th>Select Product</th>
  </tr>
  </thead>

	<tbody>
  <% @products.each do |product| %>
  <tr>
    <td><%= check_box_tag "products", product.id  %></td>
    <td><%= product.id %></td>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>
    <td><%= product.rating %></td>
    <td><%= link_to "Select", category_products_path(product.id), class: "btn btn-info" %></td>
  </tr>
  <% end %>
	</tbody>

</table>

<%= link_to 'Back', categories_path, class: "btn btn-info" %>

app/views/shared/_footer.html.erb
<footer class= "footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

<style>
  .footer { background-color: #f5f5f5; }
</style>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Inventory Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>